- hosts: all
  connection: local
  gather_facts: no

  tasks:
    - name: Get Available Templates
      uri:
        url: "https://{{ansible_host}}:8006/api2/json/nodes/localhost/storage/local/content"
        method: GET
        status_code: 200
        validate_certs: no
        headers:
          Cookie: "PVEAuthCookie={{ pve_cookie }}"
          CSRFPreventionToken: "{{ pve_csrf_token }}"
      register: pve_templates
      delegate_to: localhost

     
    - name: Create PVE Survey Spec 
      uri:
        url: "https://ansibletower.company.com/api/v2/job_templates/16/survey_spec/"
        user: "{{ api_user }}"
        password: "{{ api_password }}"
        force_basic_auth: yes
        method: POST
        body: "{{ lookup('template','templates/survey.j2') }}"
        body_format: json
        status_code: 200
        validate_certs: no
      delegate_to: localhost
